#!/usr/bin/python3

import smtplib
from email.mime.text import MIMEText
from email.header import Header

# 第三方 SMTP 服务
mail_host = "smtp.163.com"  # 设置服务器
mail_user = "XXXXXXX@163.com"  # 用户名
mail_pass = "XXXXX"  # 口令，163授权码，不是密码

sender = 'XXXXX@163.com'
receivers = ['XXXXXX@qq.com']  # 接收邮件，可设置为你的QQ邮箱或者其他邮箱
content='…………………………这里是邮件的正文内容…………………………'

message = MIMEText(content, 'plain', 'utf-8')
message['From'] = "{}".format(sender)
message['To'] = ",".join(receivers)
subject = '………………这里写邮件的主题………………………………'
message['Subject'] = Header(subject, 'utf-8')

try:
    smtpObj = smtplib.SMTP()
    smtpObj.connect(mail_host, 25)  # 25 为 SMTP 端口号
    smtpObj.login(mail_user, mail_pass)
    smtpObj.sendmail(sender, receivers, message.as_string())
    print("邮件发送成功")
except smtplib.SMTPException:
    print("Error: 无法发送邮件")
